### ISSUE TITLE
RC4 Encryption not detected

### ISSUE THREAD

**Issue by phatair** [PaulHCode/20221108-msDS-SupportedEncryptionTypes#1]
Hello Paul,

first, thanks a lot for this great script.
But i have one problem.

In our EventLog i can see, that one server use the RC4 encryption. 
![image](https://user-images.githubusercontent.com/28873754/215715842-4eb93152-2367-4b6a-9fa2-65df68fb4ec2.png)

If i look at the AD object, i can see that the msDS-SupportedEncryptionTypes is empty.
I checked other servers and clients, on this AD objects the msDS-SupportedEncryptionTypes is filled with 28 (RC4, AES 128, AES 256).

If i run your script, i would expect, that this server is shown but i get this result:
![image](https://user-images.githubusercontent.com/28873754/215716530-d040515f-af2a-4f16-85f1-2599b23b906f.png)

If u run the command
$computers | `
select name,'msDS-SupportedEncryptionTypes', @{N='EncryptionTypes';E={Get-ETypeDefinition -msDSSupportedEncryptionTypes ($_.'msDS-SupportedEncryptionTypes')}}, @{N='EncryptionTypesAsString';E={Get-ETypeDefinition -msDSSupportedEncryptionTypes ($_.'msDS-SupportedEncryptionTypes') -AsString}} | `
select name,EncryptionTypes,@{N='HasRC4OrIsBlank';E={$_.EncryptionTypesAsString -like "*RC4*"}} | `
Where{-not $_.HasRC4OrIsBlank}

I dont get any result.
What did i wrong or did i misunderstand something?

i thougt i would see the computer objects where the msDS-SupportedEncryptionTypes is empty.
Thanks a lot.
Best regards

**Comment by PaulHCode** [comment]
If you only want the computers with the msDS-SupportedEncryptionTypes attribute not defined then this will do it:

`
$computers | 
    select name,`
    'msDS-SupportedEncryptionTypes', `
    @{N='EncryptionTypes';E={Get-ETypeDefinition -msDSSupportedEncryptionTypes ($_.'msDS-SupportedEncryptionTypes')}} | 
    Where{$_.'msDS-SupportedEncryptionTypes' -eq $Null}
`

Sample output:
| name  | msDS-SupportedEncryptionTypes | EncryptionTypes |
| ------  | --------------------------------------  | ------------------ |
| LongForgottenComputer | | Not defined - defaults to RC4_HMAC_MD5 |


Blank isn't a problem, and supporting RC4 isn't a problem, only stuff doesn't support RC4 and isn't blank is a problem so my column "HasRC4OrIsBlank" only shows items that will have a problem if the patch were applied. I fixed the query you provided and posted it below.

`
$computers |select name,'msDS-SupportedEncryptionTypes',@{N='EncryptionTypes';E={Get-ETypeDefinition -msDSSupportedEncryptionTypes ($.'msDS-SupportedEncryptionTypes')}},  @{N='EncryptionTypesAsString';E={Get-ETypeDefinition -msDSSupportedEncryptionTypes ($_.'msDS-SupportedEncryptionTypes') -AsString}} | select name,EncryptionTypes,@{N='HasRC4OrIsBlank';E={$_.EncryptionTypesAsString -like "*RC4*"}} |where{-not $_.HasRC4OrIsBlank}
`

sample output:
| name | EncryptionTypes | HasRC4OrIsBlank |
| ------ | ------------------ | ------------------- |
| test6 | AES 128 | False |
| VeryImportantComputer | AES 128 | False |
